# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JR0AiBh9b1NyigybDKwqS8vKTUfa8iXg
"""

# ontador de islas
mat = [[0,0,1,1], 
       [0,0,1,1], 
       [1,1,0,0],
       [0,0,0,1]]

contadorIslas = 0

def llamarDFS(grilla,i,j):  
  if i < 0 or i >= len(grilla) or j < 0 or j >= len(grilla) or grilla[i][j] == 0:
    return 0
  else:
    grilla[i][j] = 0   # lo vuelvo cero o ya visitado
    llamarDFS(grilla,i+1,j) # arriba
    llamarDFS(grilla,i-1,j) #abajo
    llamarDFS(grilla,i,j-1) #lados
    llamarDFS(grilla,i,j+1)

   

for i in range(0,len(mat)):
  for j in range(0,len(mat[:][1])):
    print(i,j)
    if mat[i][j] == 1:
      contadorIslas += 1
      llamarDFS(mat,i,j)

print(contadorIslas)